### PR TITLE
Home section done

### PR DESCRIPTION
**Pull request by fmb97**

### CODE REVIEW

**Comment by nasser-31** [comment]
Thanks Feras!
I checked out what you sent me!
but I have some notes before merging the changes:
- Can you please change the h3 you used and use paragraphs tags instead of tehm?
-can you remove the background size! since it doesn't help in the big screens!
Thanks 
It's really a great work done by you!

**Comment by fmb97** [comment]
The changes requested are added to the latest commit, thanks for helping.

**Comment by nasser-31** [comment]
great job!
but can you take care of lthe links "linkedin amazon in which they are below the header image"

**Comment by nasser-31** [comment]
well done please, edit the links in the mobile version they are collapsing

**Pull request merged**
